controller_joint_names: ['', 'rjoint11', 'pjoint11', 'rjoint12', 'pjoint12', 'rjoint13', 'pjoint13', 'rjoint14', 'pjoint14', 'rjoint21', 'pjoint21', 'rjoint22', 'pjoint22', 'rjoint23', 'pjoint23', 'rjoint24', 'pjoint24', 'linkjoint12', ]
